name: Generate Streak Stats

on:
  schedule:
  - cron: "0 9 * * *" # Jam 09:00 UTC / Jam 16:00 WIB
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  streak:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate streak stats SVG
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=ejeee&hide_border=true&background=00000000&ring=2563EB&fire=38BDF8&currStreakLabel=4A709C&sideLabels=94A3B8&currStreakNum=4A709C&sideNums=E6F7FF&dates=64748B
          path: assets/github-streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "today=$(date -u +%F)" >> $GITHUB_OUTPUT

      - name: Commit & Push files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update streak stats: ${{ steps.date.outputs.today }} [skip ci]"
          add: "assets/github-streak.svg"
